[workspace]
resolver = "2"
members = ["apps/*", "crates/*"]
package.edition = "2021"
package.version = "0.1.0"

[workspace.dependencies]
chrono = "0.4"
log = { version = "0.4", features = ["std"] }
libc = "0.2"
lazy_static = "1.4.0"
